# This file contains values from Cookiecutter

#default_context:
#  project_name: "pycounts_ja2327072339"
#  project_description: "Awesome `pycounts_ja2327072339` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
#  organization: "pycounts_ja2327072339"
#  license: "MIT"
#  minimal_python_version: 3.9
#  github_name: "pycounts_ja2327072339"
#  email: "eliseetegue@gmail.com"
#  version: "0.1.0"
#  line_length: "88"
#  create_example_template: "cli"
